<a href="https://colab.research.google.com/github/sanket2843/kestrel-returns/blob/main/Analysis3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.io as pio
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import nltk
import webbrowser
import os

In [ ]:
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\vaish\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [ ]:
apps_df=pd.read_csv('Play Store Data.csv')
reviews_df=pd.read_csv('User Reviews.csv')

In [ ]:
apps_df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [ ]:
reviews_df.head()

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
2,10 Best Foods for You,NaN,NaN,NaN,NaN
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000

In [ ]:
#pd.read_csv() : csv files
#pd.read_excel() : excel files
#pd.read_sql() : SQL Databases
#pd.read_json() : JSON Files

In [ ]:
#df.isnull() : Missing values
#df.dropna() : Removes rows and columns that contain the missing values
#df.fillna() : Fills missing values

In [ ]:
#df.duplicated() : Identifies duplicates
#df.drop_duplicates() : Removes duplicate rows

In [ ]:
#Step 2 : Data Cleaning
apps_df = apps_df.dropna(subset=['Rating'])
for column in apps_df.columns :
    apps_df[column].fillna(apps_df[column].mode()[0],inplace=True)
apps_df.drop_duplicates(inplace=True)
apps_df=apps_df=apps_df[apps_df['Rating']<=5]
reviews_df.dropna(subset=['Translated_Review'],inplace=True)

C:\Users\vaish\AppData\Local\Temp\ipykernel_288\2487222361.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  apps_df[column].fillna(apps_df[column].mode()[0],inplace=True)

In [ ]:
apps_df.dtypes

App                object
Category           object
Rating            float64
Reviews            object
Size               object
Installs           object
Type               object
Price              object
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
dtype: object

In [ ]:
#Convert the Installs columns to numeric by removing commas and +
apps_df['Installs']=apps_df['Installs'].str.replace(',','').str.replace('+','').astype(int)

#Convert Price column to numeric after removing $
apps_df['Price']=apps_df['Price'].str.replace('$','').astype(float)

In [ ]:
apps_df.dtypes

App                object
Category           object
Rating            float64
Reviews            object
Size               object
Installs            int32
Type               object
Price             float64
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
dtype: object

In [ ]:
merged_df=pd.merge(apps_df,reviews_df,on='App',how='inner')

In [ ]:
merged_df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,500000,Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,A kid's excessive ads. The types ads allowed a...,Negative,-0.250,1.000000
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,500000,Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,It bad >:(,Negative,-0.725,0.833333
2,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,500000,Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,like,Neutral,0.000,0.000000
3,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,500000,Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,I love colors inspyering,Positive,0.500,0.600000
4,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,500000,Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,I hate,Negative,-0.800,0.900000

In [ ]:
def convert_size(size):
    if 'M' in size:
        return float(size.replace('M',''))
    elif 'k' in size:
        return float(size.replace('k',''))/1024
    else:
        return np.nan
apps_df['Size']=apps_df['Size'].apply(convert_size)

In [ ]:
apps_df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,10000,Free,0.0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,5000000,Free,0.0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,50000000,Free,0.0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0.0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10834,FR Calculator,FAMILY,4.0,7,2.6,500,Free,0.0,Everyone,Education,"June 18, 2017",1.0.0,4.1 and up
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53.0,5000,Free,0.0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6,100,Free,0.0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,NaN,1000,Free,0.0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19.0,10000000,Free,0.0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [ ]:
#Lograrithmic
apps_df['Log_Installs']=np.log(apps_df['Installs'])

In [ ]:
apps_df['Reviews']=apps_df['Reviews'].astype(int)

In [ ]:
apps_df['Log_Reviews']=np.log(apps_df['Reviews'])

In [ ]:
apps_df.dtypes

App                object
Category           object
Rating            float64
Reviews             int32
Size              float64
Installs            int32
Type               object
Price             float64
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
Log_Installs      float64
Log_Reviews       float64
dtype: object

In [ ]:
def rating_group(rating):
    if rating >= 4:
        return 'Top rated app'
    elif rating >=3:
        return 'Above average'
    elif rating >=2:
        return 'Average'
    else:
        return 'Below Average'
apps_df['Rating_Group']=apps_df['Rating'].apply(rating_group)

In [ ]:
#Revenue column
apps_df['Revenue']=apps_df['Price']*apps_df['Installs']

In [ ]:
sia = SentimentIntensityAnalyzer()

In [ ]:
#Polarity Scores in SIA
#Positive, Negative, Neutral and Compound: -1 - Very negative ; +1 - Very positive

In [ ]:
review = "This app is amazing! I love the new features."
sentiment_score= sia.polarity_scores(review)
print(sentiment_score)

{'neg': 0.0, 'neu': 0.42, 'pos': 0.58, 'compound': 0.8516}

In [ ]:
review = "This app is very bad! I hate the new features."
sentiment_score= sia.polarity_scores(review)
print(sentiment_score)

{'neg': 0.535, 'neu': 0.465, 'pos': 0.0, 'compound': -0.8427}

In [ ]:
review = "This app is okay."
sentiment_score= sia.polarity_scores(review)
print(sentiment_score)

{'neg': 0.0, 'neu': 0.612, 'pos': 0.388, 'compound': 0.2263}

In [ ]:
reviews_df['Sentiment_Score']=reviews_df['Translated_Review'].apply(lambda x: sia.polarity_scores(str(x))['compound'])

In [ ]:
reviews_df.head()

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity,Sentiment_Score
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333,0.9531
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462,0.6597
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000,0.6249
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000,0.6369
5,10 Best Foods for You,Best way,Positive,1.00,0.300000,0.6369

In [ ]:
apps_df['Last Updated']=pd.to_datetime(apps_df['Last Updated'],errors='coerce')

In [ ]:
apps_df['Year']=apps_df['Last Updated'].dt.year

In [ ]:
apps_df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Log_Installs,Log_Reviews,Rating_Group,Revenue,Year
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,10000,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,9.210340,5.068904,Top rated app,0.0,2018
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,13.122363,6.874198,Above average,0.0,2018
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,5000000,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,15.424948,11.379508,Top rated app,0.0,2018
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,50000000,Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,17.727534,12.281384,Top rated app,0.0,2018
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,11.512925,6.874198,Top rated app,0.0,2018

In [ ]:
html_files_path="./"
if not os.path.exists(html_files_path):
    os.makedirs(html_files_path)

In [ ]:
plot_containers=""

In [ ]:
# Save each Plotly figure to an HTML file
def save_plot_as_html(fig, filename, insight):
    global plot_containers
    filepath = os.path.join(html_files_path, filename)
    html_content = pio.to_html(fig, full_html=False, include_plotlyjs='inline')
    # Append the plot and its insight to plot_containers
    plot_containers += f"""
    <div class="plot-container" id="{filename}" onclick="openPlot('{filename}')">
        <div class="plot">{html_content}</div>
        <div class="insights">{insight}</div>
    </div>
    """
    fig.write_html(filepath, full_html=False, include_plotlyjs='inline')

In [ ]:
plot_width=400
plot_height=300
plot_bg_color='black'
text_color='white'
title_font={'size':16}
axis_font={'size':12}

In [ ]:
#Figure 1
category_counts=apps_df['Category'].value_counts().nlargest(10)
fig1=px.bar(
    x=category_counts.index,
    y=category_counts.values,
    labels={'x':'Category','y':'Count'},
    title='Top Categories on Play Store',
    color=category_counts.index,
    color_discrete_sequence=px.colors.sequential.Plasma,
    width=400,
    height=300
)
fig1.update_layout(
    plot_bgcolor='black',
    paper_bgcolor='black',
    font_color='white',
    title_font={'size':16},
    xaxis=dict(title_font={'size':12}),
    yaxis=dict(title_font={'size':12}),
    margin=dict(l=10,r=10,t=30,b=10)
)
#fig1.update_traces(marker=dict(pattern=dict(line=dict(color='white',width=1))))
save_plot_as_html(fig1,"Category Graph 1.html","The top categories on the Play Store are dominated by tools, entertainment, and productivity apps")

In [ ]:
#Figure 2
type_counts=apps_df['Type'].value_counts()
fig2=px.pie(
    values=type_counts.values,
    names=type_counts.index,
    title='App Type Distribution',
    color_discrete_sequence=px.colors.sequential.RdBu,
    width=400,
    height=300
)
fig2.update_layout(
    plot_bgcolor='black',
    paper_bgcolor='black',
    font_color='white',
    title_font={'size':16},
    margin=dict(l=10,r=10,t=30,b=10)
)
#fig1.update_traces(marker=dict(pattern=dict(line=dict(color='white',width=1))))
save_plot_as_html(fig2,"Type Graph 2.html","Most apps on the Playstore are free, indicating a strategy to attract users first and monetize through ads or in app purchases")

In [ ]:
#Figure 3
fig3=px.histogram(
    apps_df,
    x='Rating',
    nbins=20,
    title='Rating Distribution',
    color_discrete_sequence=['#636EFA'],
    width=400,
    height=300
)
fig3.update_layout(
    plot_bgcolor='black',
    paper_bgcolor='black',
    font_color='white',
    title_font={'size':16},
    xaxis=dict(title_font={'size':12}),
    yaxis=dict(title_font={'size':12}),
    margin=dict(l=10,r=10,t=30,b=10)
)
#fig1.update_traces(marker=dict(pattern=dict(line=dict(color='white',width=1))))
save_plot_as_html(fig3,"Rating Graph 3.html","Ratings are skewed towards higher values, suggesting that most apps are rated favorably by users")

In [ ]:
#Figure 4
sentiment_counts=reviews_df['Sentiment_Score'].value_counts()
fig4=px.bar(
    x=sentiment_counts.index,
    y=sentiment_counts.values,
    labels={'x':'Sentiment Score','y':'Count'},
    title='Sentiment Distribution',
    color=sentiment_counts.index,
    color_discrete_sequence=px.colors.sequential.RdPu,
    width=400,
    height=300
)
fig4.update_layout(
    plot_bgcolor='black',
    paper_bgcolor='black',
    font_color='white',
    title_font={'size':16},
    xaxis=dict(title_font={'size':12}),
    yaxis=dict(title_font={'size':12}),
    margin=dict(l=10,r=10,t=30,b=10)
)
#fig1.update_traces(marker=dict(pattern=dict(line=dict(color='white',width=1))))
save_plot_as_html(fig4,"Sentiment Graph 4.html","Sentiments in reviews show a mix of positive and negative feedback, with a slight lean towards positive sentiments")

In [ ]:
#Figure 5
installs_by_category=apps_df.groupby('Category')['Installs'].sum().nlargest(10)
fig5=px.bar(
    x=installs_by_category.index,
    y=installs_by_category.values,
    orientation='h',
    labels={'x':'Installs','y':'Category'},
    title='Installs by Category',
    color=installs_by_category.index,
    color_discrete_sequence=px.colors.sequential.Blues,
    width=400,
    height=300
)
fig5.update_layout(
    plot_bgcolor='black',
    paper_bgcolor='black',
    font_color='white',
    title_font={'size':16},
    xaxis=dict(title_font={'size':12}),
    yaxis=dict(title_font={'size':12}),
    margin=dict(l=10,r=10,t=30,b=10)
)
#fig1.update_traces(marker=dict(pattern=dict(line=dict(color='white',width=1))))
save_plot_as_html(fig5,"Installs Graph 5.html","The categories with the most installs are social and communication apps, reflecting their broad appeal and daily usage")

In [ ]:
# Updates Per Year Plot
updates_per_year = apps_df['Last Updated'].dt.year.value_counts().sort_index()
fig6 = px.line(
    x=updates_per_year.index,
    y=updates_per_year.values,
    labels={'x': 'Year', 'y': 'Number of Updates'},
    title='Number of Updates Over the Years',
    color_discrete_sequence=['#AB63FA'],
    width=plot_width,
    height=plot_height
)
fig6.update_layout(
    plot_bgcolor=plot_bg_color,
    paper_bgcolor=plot_bg_color,
    font_color=text_color,
    title_font=title_font,
    xaxis=dict(title_font=axis_font),
    yaxis=dict(title_font=axis_font),
    margin=dict(l=10, r=10, t=30, b=10)
)
save_plot_as_html(fig6, "Updates Graph 6.html", "Updates have been increasing over the years, showing that developers are actively maintaining and improving their apps.")

In [ ]:
#Figure 7
revenue_by_category=apps_df.groupby('Category')['Revenue'].sum().nlargest(10)
fig7=px.bar(
    x=installs_by_category.index,
    y=installs_by_category.values,
    labels={'x':'Category','y':'Revenue'},
    title='Revenue by Category',
    color=installs_by_category.index,
    color_discrete_sequence=px.colors.sequential.Greens,
    width=400,
    height=300
)
fig7.update_layout(
    plot_bgcolor='black',
    paper_bgcolor='black',
    font_color='white',
    title_font={'size':16},
    xaxis=dict(title_font={'size':12}),
    yaxis=dict(title_font={'size':12}),
    margin=dict(l=10,r=10,t=30,b=10)
)
#fig1.update_traces(marker=dict(pattern=dict(line=dict(color='white',width=1))))
save_plot_as_html(fig7,"Revenue Graph 7.html","Categories such as Business and Productivity lead in revenue generation, indicating their monetization potential")

In [ ]:
#Figure 8
genre_counts=apps_df['Genres'].str.split(';',expand=True).stack().value_counts().nlargest(10)
fig8=px.bar(
    x=genre_counts.index,
    y=genre_counts.values,
    labels={'x':'Genre','y':'Count'},
    title='Top Genres',
    color=installs_by_category.index,
    color_discrete_sequence=px.colors.sequential.OrRd,
    width=400,
    height=300
)
fig8.update_layout(
    plot_bgcolor='black',
    paper_bgcolor='black',
    font_color='white',
    title_font={'size':16},
    xaxis=dict(title_font={'size':12}),
    yaxis=dict(title_font={'size':12}),
    margin=dict(l=10,r=10,t=30,b=10)
)
#fig1.update_traces(marker=dict(pattern=dict(line=dict(color='white',width=1))))
save_plot_as_html(fig8,"Genre Graph 8.html","Action and Casual genres are the most common, reflecting users' preference for engaging and easy-to-play games")

In [ ]:
#Figure 9
fig9=px.scatter(
    apps_df,
    x='Last Updated',
    y='Rating',
    color='Type',
    title='Impact of Last Update on Rating',
    color_discrete_sequence=px.colors.qualitative.Vivid,
    width=400,
    height=300
)
fig9.update_layout(
    plot_bgcolor='black',
    paper_bgcolor='black',
    font_color='white',
    title_font={'size':16},
    xaxis=dict(title_font={'size':12}),
    yaxis=dict(title_font={'size':12}),
    margin=dict(l=10,r=10,t=30,b=10)
)
#fig1.update_traces(marker=dict(pattern=dict(line=dict(color='white',width=1))))
save_plot_as_html(fig9,"Update Graph 9.html","The Scatter Plot shows a weak correlation between the last update and ratings, suggesting that more frequent updates dont always result in better ratings.")

In [ ]:
#Figure 10
fig10=px.box(
    apps_df,
    x='Type',
    y='Rating',
    color='Type',
    title='Rating for Paid vs Free Apps',
    color_discrete_sequence=px.colors.qualitative.Pastel,
    width=400,
    height=300
)
fig10.update_layout(
    plot_bgcolor='black',
    paper_bgcolor='black',
    font_color='white',
    title_font={'size':16},
    xaxis=dict(title_font={'size':12}),
    yaxis=dict(title_font={'size':12}),
    margin=dict(l=10,r=10,t=30,b=10)
)
#fig1.update_traces(marker=dict(pattern=dict(line=dict(color='white',width=1))))
save_plot_as_html(fig10,"Paid Free Graph 10.html","Paid apps generally have higher ratings compared to free apps, suggesting that users expect higher quality from apps they pay for")

In [ ]:
plot_containers_split=plot_containers.split('</div>')

In [ ]:
if len(plot_containers_split) > 1:
    final_plot=plot_containers_split[-2]+'</div>'
else:
    final_plot=plot_containers

In [ ]:
dashboard_html= """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name=viewport" content="width=device-width,initial-scale-1.0">
    <title> Google Play Store Review Analytics</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            background-color: #333;
            color: #fff;
            margin: 0;
            padding: 0;
        }}
        .header {{
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 20px;
            background-color: #444
        }}
        .header img {{
            margin: 0 10px;
            height: 50px;
        }}
        .container {{
            display: flex;
            flex-wrap: wrap;
            justify_content: center;
            padding: 20px;
        }}
        .plot-container {{
            border: 2px solid #555
            margin: 10px;
            padding: 10px;
            width: {plot_width}px;
            height: {plot_height}px;
            overflow: hidden;
            position: relative;
            cursor: pointer;
        }}
        .insights {{
            display: none;
            position: absolute;
            right: 10px;
            top: 10px;
            background-color: rgba(0,0,0,0.7);
            padding: 5px;
            border-radius: 5px;
            color: #fff;
        }}
        .plot-container: hover .insights {{
            display: block;
        }}
        </style>
        <script>
            function openPlot(filename) {{
                window.open(filename, '_blank');
                }}
        </script>
    </head>
    <body>
        <div class= "header">
            <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Logo_2013_Google.png/800px-Logo_2013_Google.png" alt="Google Logo">
            <h1>Google Play Store Reviews Analytics</h1>
            <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Google_Play_Store_badge_EN.svg/1024px-Google_Play_Store_badge_EN.svg.png" alt="Google Play Store Logo">
        </div>
        <div class="container">
            {plots}
        </div>
    </body>
    </html>
    """

In [ ]:
final_html=dashboard_html.format(plots=plot_containers,plot_width=plot_width,plot_height=plot_height)

In [ ]:
dashboard_path=os.path.join(html_files_path,"web page.html")

In [ ]:
with open(dashboard_path, "w", encoding="utf-8") as f:
    f.write(final_html)

In [ ]:
webbrowser.open('file://'+os.path.realpath(dashboard_path))

True

In [1]:
import pandas as pd

# Load the Play Store dataset
url = "https://raw.githubusercontent.com/vaish-vkb/Google-Play-Store-Analytics/main/Play%20Store%20Data.csv"
df = pd.read_csv(url)

# Clean the Installs column
df["Installs"] = (
    df["Installs"].astype(str)
    .str.replace(",", "", regex=False)
    .str.replace("+", "", regex=False)
)

df["Installs"] = pd.to_numeric(df["Installs"], errors="coerce")

# Calculate total installs by category
category_installs = (
    df.groupby("Category", as_index=False)["Installs"]
    .sum()
    .sort_values("Installs", ascending=False)
)

# Show the top 5 categories
top5 = category_installs.head(5)
print(top5)

         Category      Installs
15           GAME  3.508602e+10
7   COMMUNICATION  3.264728e+10
26   PRODUCTIVITY  1.417609e+10
28         SOCIAL  1.406987e+10
30          TOOLS  1.145277e+10

In [2]:
# Remove categories starting with A, C, G, or S
filtered_categories = category_installs[
    ~category_installs["Category"].str.startswith(("A", "C", "G", "S"))
]

# Get the top 5 remaining categories
top5_filtered = filtered_categories.head(5)

print(top5_filtered)

              Category      Installs
26        PRODUCTIVITY  1.417609e+10
30               TOOLS  1.145277e+10
12              FAMILY  1.025826e+10
25         PHOTOGRAPHY  1.008825e+10
22  NEWS_AND_MAGAZINES  7.496318e+09

In [3]:
# Highlight categories with more than 1 million installs
top5_filtered["Highlight"] = top5_filtered["Installs"].apply(
    lambda x: "Above 1 Million" if x > 1_000_000 else "1 Million or Less"
)

print(top5_filtered)

              Category      Installs        Highlight
26        PRODUCTIVITY  1.417609e+10  Above 1 Million
30               TOOLS  1.145277e+10  Above 1 Million
12              FAMILY  1.025826e+10  Above 1 Million
25         PHOTOGRAPHY  1.008825e+10  Above 1 Million
22  NEWS_AND_MAGAZINES  7.496318e+09  Above 1 Million

/tmp/ipykernel_616/4139545503.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top5_filtered["Highlight"] = top5_filtered["Installs"].apply(

In [4]:
top5_filtered = top5_filtered.copy()

top5_filtered["Highlight"] = top5_filtered["Installs"].apply(
    lambda x: "Above 1 Million" if x > 1_000_000 else "1 Million or Less"
)

print(top5_filtered)

              Category      Installs        Highlight
26        PRODUCTIVITY  1.417609e+10  Above 1 Million
30               TOOLS  1.145277e+10  Above 1 Million
12              FAMILY  1.025826e+10  Above 1 Million
25         PHOTOGRAPHY  1.008825e+10  Above 1 Million
22  NEWS_AND_MAGAZINES  7.496318e+09  Above 1 Million

In [5]:
import plotly.express as px

fig = px.bar(
    top5_filtered,
    x="Category",
    y="Installs",
    color="Highlight",
    title="Top 5 App Categories by Total Installs",
    labels={
        "Category": "App Category",
        "Installs": "Total Installs"
    },
    color_discrete_map={
        "Above 1 Million": "green",
        "1 Million or Less": "lightgray"
    }
)

fig.update_layout(
    xaxis_tickangle=-30,
    template="plotly_white"
)

fig.show()

In [6]:
print("Available columns:")
print(df.columns.tolist())

print("\nDataset shape:")
print(df.shape)

print("\nSample data:")
display(df.head(5))

Available columns:
['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type', 'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver', 'Android Ver']

Dataset shape:
(10841, 13)

Sample data:

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,10000.0,Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,500000.0,Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,5000000.0,Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,50000000.0,Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,100000.0,Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [7]:
from datetime import datetime
from zoneinfo import ZoneInfo

now_ist = datetime.now(ZoneInfo("Asia/Kolkata"))
current_time = now_ist.time()

start_time = datetime.strptime("18:00", "%H:%M").time()
end_time = datetime.strptime("20:00", "%H:%M").time()

if start_time <= current_time < end_time:
    print("Task 2 dashboard is available now.")
    fig.show()
else:
    print("Task 2 dashboard is hidden. Available daily from 6 PM to 8 PM IST.")

Task 2 dashboard is hidden. Available daily from 6 PM to 8 PM IST.

In [8]:
print("Categories:", df["Category"].nunique())
print("Total installs:", df["Installs"].sum())
print("Country column available:", any(
    "country" in col.lower() for col in df.columns
))

Categories: 34
Total installs: 167633433487.0
Country column available: False

In [9]:
import plotly.express as px

fig = px.bar(
    top5_filtered,
    x="Category",
    y="Installs",
    color="Highlight",
    title="Task 2: Top 5 App Categories by Installs",
    labels={
        "Category": "App Category",
        "Installs": "Total Installs"
    },
    color_discrete_map={
        "Above 1 Million": "green",
        "1 Million or Less": "lightgray"
    }
)

fig.update_layout(
    template="plotly_white",
    xaxis_tickangle=-30
)

fig.show()

In [10]:
from datetime import datetime
from zoneinfo import ZoneInfo

now_ist = datetime.now(ZoneInfo("Asia/Kolkata"))
current_time = now_ist.hour * 60 + now_ist.minute

start_time = 18 * 60   # 6 PM
end_time = 20 * 60     # 8 PM

if start_time <= current_time < end_time:
    print("Task 2 chart is available.")
    fig.show()
else:
    print("Task 2 chart is hidden. Available from 6 PM to 8 PM IST.")

Task 2 chart is hidden. Available from 6 PM to 8 PM IST.

In [11]:

import pandas as pd
import numpy as np
import plotly.express as px
from datetime import datetime
from zoneinfo import ZoneInfo

url = "https://raw.githubusercontent.com/vaish-vkb/Google-Play-Store-Analytics/main/Play%20Store%20Data.csv"
df = pd.read_csv(url)

print("Dataset loaded successfully!")
print("Rows and columns:", df.shape)
print("Available columns:")
print(df.columns.tolist())

Dataset loaded successfully!
Rows and columns: (10841, 13)
Available columns:
['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type', 'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver', 'Android Ver']

In [12]:

# Clean the required columns

df["App"] = df["App"].astype(str).str.strip()
df["Category"] = df["Category"].astype(str).str.strip()

# Convert Reviews to numeric
df["Reviews"] = pd.to_numeric(df["Reviews"], errors="coerce")

# Clean Installs and convert to numeric
df["Installs"] = (
    df["Installs"].astype(str)
    .str.replace(",", "", regex=False)
    .str.replace("+", "", regex=False)
)

df["Installs"] = pd.to_numeric(df["Installs"], errors="coerce")

# Convert Last Updated to datetime
df["Last Updated"] = pd.to_datetime(
    df["Last Updated"],
    errors="coerce"
)

# Apply Task 3 filters
filtered_df = df[
    (df["Reviews"] > 500) &
    (~df["App"].str.upper().str.startswith(("X", "Y", "Z"))) &
    (~df["App"].str.upper().str.contains("S", regex=False)) &
    (df["Category"].str.upper().str.startswith(("E", "C", "B")))
].copy()

# Remove rows missing required values
filtered_df = filtered_df.dropna(
    subset=["Installs", "Last Updated", "Category"]
)

print("Rows after filtering:", len(filtered_df))
print("\nCategories included:")
print(sorted(filtered_df["Category"].unique()))
print("\nDate range:")
print(filtered_df["Last Updated"].min(), "to",
      filtered_df["Last Updated"].max())

Rows after filtering: 245

Categories included:
['BEAUTY', 'BOOKS_AND_REFERENCE', 'BUSINESS', 'COMICS', 'COMMUNICATION', 'EDUCATION', 'ENTERTAINMENT', 'EVENTS']

Date range:
2014-01-15 00:00:00 to 2018-08-06 00:00:00

In [13]:

# Translate category names for display on the graph

category_translation = {
    "BEAUTY": "सौंदर्य",
    "BUSINESS": "வணிகம்",
    "DATING": "Partnersuche"
}

filtered_df["Category_Display"] = (
    filtered_df["Category"].map(category_translation)
    .fillna(filtered_df["Category"])
)

# Create month column from Last Updated
filtered_df["Month"] = (
    filtered_df["Last Updated"].dt.to_period("M").dt.to_timestamp()
)

# Calculate total installs by month and category
monthly_data = (
    filtered_df.groupby(["Month", "Category_Display"], as_index=False)
    ["Installs"].sum()
    .sort_values("Month")
)

print("Monthly data created successfully!")
print("Rows:", len(monthly_data))
print("\nSample data:")
display(monthly_data.head(10))

Monthly data created successfully!
Rows: 79

Sample data:

       Month     Category_Display    Installs
0 2014-01-01        COMMUNICATION    100000.0
1 2014-03-01        COMMUNICATION    100000.0
2 2014-05-01               வணிகம்    100000.0
3 2014-07-01        COMMUNICATION  10000000.0
4 2014-07-01            EDUCATION     10000.0
5 2014-10-01  BOOKS_AND_REFERENCE    500000.0
6 2014-11-01  BOOKS_AND_REFERENCE   5000000.0
7 2015-01-01            EDUCATION    100000.0
8 2015-03-01        COMMUNICATION   1000000.0
9 2015-06-01            EDUCATION   1000000.0

In [14]:

# Sort data by category and month
monthly_data = monthly_data.sort_values(
    ["Category_Display", "Month"]
).copy()

# Calculate previous month's installs for each category
monthly_data["Previous_Installs"] = (
    monthly_data.groupby("Category_Display")["Installs"].shift(1)
)

# Calculate percentage growth
monthly_data["Growth_Percent"] = (
    (monthly_data["Installs"] - monthly_data["Previous_Installs"])
    / monthly_data["Previous_Installs"] * 100
)

# Identify growth greater than 20%
monthly_data["Significant_Growth"] = (
    monthly_data["Growth_Percent"] > 20
)

print("Growth calculation completed!")
display(
    monthly_data[
        ["Month", "Category_Display", "Installs",
         "Previous_Installs", "Growth_Percent",
         "Significant_Growth"]
    ].head(15)
)

Growth calculation completed!

,Month,Category_Display,Installs,Previous_Installs,Growth_Percent,Significant_Growth
5,2014-10-01,BOOKS_AND_REFERENCE,500000.0,NaN,NaN,False
6,2014-11-01,BOOKS_AND_REFERENCE,5000000.0,500000.0,900.000000,True
10,2015-07-01,BOOKS_AND_REFERENCE,10000000.0,5000000.0,100.000000,True
18,2016-06-01,BOOKS_AND_REFERENCE,60000.0,10000000.0,-99.400000,False
21,2016-08-01,BOOKS_AND_REFERENCE,100000.0,60000.0,66.666667,True
27,2017-02-01,BOOKS_AND_REFERENCE,100000.0,100000.0,0.000000,False
29,2017-04-01,BOOKS_AND_REFERENCE,1000000.0,100000.0,900.000000,True
31,2017-05-01,BOOKS_AND_REFERENCE,100000.0,1000000.0,-90.000000,False
32,2017-07-01,BOOKS_AND_REFERENCE,100000.0,100000.0,0.000000,False
33,2017-08-01,BOOKS_AND_REFERENCE,10010000.0,100000.0,9910.000000,True
38,2017-11-01,BOOKS_AND_REFERENCE,2000000.0,10010000.0,-80.019980,False
49,2018-04-01,BOOKS_AND_REFERENCE,1050000.0,2000000.0,-47.500000,False
51,2018-05-01,BOOKS_AND_REFERENCE,40600000.0,1050000.0,3766.666667,True
58,2018-06-01,BOOKS_AND_REFERENCE,52100000.0,40600000.0,28.325123,True
64,2018-07-01,BOOKS_AND_REFERENCE,201600000.0,52100000.0,286.948177,True

In [15]:

import plotly.graph_objects as go

fig = go.Figure()

# Add a separate line for each category
for category in monthly_data["Category_Display"].unique():
    cat_data = (
        monthly_data[
            monthly_data["Category_Display"] == category
        ].sort_values("Month").copy()
    )

    fig.add_trace(
        go.Scatter(
            x=cat_data["Month"],
            y=cat_data["Installs"],
            mode="lines+markers",
            name=category,
            connectgaps=False,
            hovertemplate=(
                "Month: %{x|%b %Y}<br>"
                "Category: " + category + "<br>"
                "Installs: %{y:,.0f}<extra></extra>"
            )
        )
    )

    # Shade the area under the curve where growth exceeds 20%
    growth_data = cat_data[
        cat_data["Significant_Growth"] == True
    ]

    if not growth_data.empty:
        fig.add_trace(
            go.Scatter(
                x=growth_data["Month"],
                y=growth_data["Installs"],
                mode="markers",
                marker=dict(color="red", size=10, symbol="diamond"),
                name=f"{category} — Growth >20%",
                showlegend=True,
                hovertemplate=(
                    "Month: %{x|%b %Y}<br>"
                    "Installs: %{y:,.0f}<br>"
                    "Growth >20%<extra></extra>"
                )
            )
        )

fig.update_layout(
    title="Monthly App Installs Trend by Category",
    xaxis_title="Month",
    yaxis_title="Total Installs",
    yaxis_type="log",
    template="plotly_white",
    hovermode="x unified",
    legend_title="App Category",
    height=650
)

fig.show()

In [16]:

import plotly.graph_objects as go

fig = go.Figure()
growth_legend_added = False

# Create a line for each app category
for category in monthly_data["Category_Display"].unique():

    cat_data = (
        monthly_data[
            monthly_data["Category_Display"] == category
        ]
        .sort_values("Month")
        .copy()
        .reset_index(drop=True)
    )

    # Main category line
    fig.add_trace(
        go.Scatter(
            x=cat_data["Month"],
            y=cat_data["Installs"],
            mode="lines+markers",
            name=category,
            connectgaps=False,
            hovertemplate=(
                "Month: %{x|%b %Y}<br>"
                "Category: " + category + "<br>"
                "Installs: %{y:,.0f}<extra></extra>"
            )
        )
    )

    # Shade under the curve where growth exceeds 20%
    for i in range(1, len(cat_data)):

        previous_row = cat_data.iloc[i - 1]
        current_row = cat_data.iloc[i]

        if current_row["Significant_Growth"]:

            fig.add_trace(
                go.Scatter(
                    x=[
                        previous_row["Month"],
                        current_row["Month"]
                    ],
                    y=[
                        previous_row["Installs"],
                        current_row["Installs"]
                    ],
                    mode="lines",
                    line=dict(
                        color="rgba(255, 0, 0, 0.35)",
                        width=3
                    ),
                    fill="tozeroy",
                    fillcolor="rgba(255, 0, 0, 0.18)",
                    name="Growth >20%",
                    legendgroup="growth",
                    showlegend=not growth_legend_added,
                    hoverinfo="skip"
                )
            )

            growth_legend_added = True

    # Highlight significant growth points
    growth_data = cat_data[
        cat_data["Significant_Growth"]
    ]

    if not growth_data.empty:
        fig.add_trace(
            go.Scatter(
                x=growth_data["Month"],
                y=growth_data["Installs"],
                mode="markers",
                marker=dict(
                    color="red",
                    size=9,
                    symbol="diamond"
                ),
                name=f"{category} growth points",
                showlegend=False,
                hovertemplate=(
                    "Month: %{x|%b %Y}<br>"
                    "Installs: %{y:,.0f}<br>"
                    "Growth exceeds 20%<extra></extra>"
                )
            )
        )

# Chart layout
fig.update_layout(
    title="Monthly App Installs Trend by Category",
    xaxis_title="Month",
    yaxis_title="Total Installs",
    yaxis_type="log",
    template="plotly_white",
    hovermode="closest",
    legend_title="App Category",
    height=650
)

fig.show()

In [17]:

from datetime import datetime
from zoneinfo import ZoneInfo

now_ist = datetime.now(ZoneInfo("Asia/Kolkata"))
current_time = now_ist.hour * 60 + now_ist.minute

start_time = 18 * 60  # 6:00 PM
end_time = 21 * 60    # 9:00 PM

if start_time <= current_time < end_time:
    print("Chart is available now (6 PM - 9 PM IST).")
    fig.show()
else:
    print("Chart is hidden. Available daily from 6 PM to 9 PM IST.")

Chart is hidden. Available daily from 6 PM to 9 PM IST.

In [18]:

import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import re
from datetime import datetime
from zoneinfo import ZoneInfo

url = "https://raw.githubusercontent.com/vaish-vkb/Google-Play-Store-Analytics/main/Play%20Store%20Data.csv"

df4 = pd.read_csv(url)

print("Task 4 dataset loaded successfully!")
print("Rows and columns:", df4.shape)
print(df4.columns.tolist())

Task 4 dataset loaded successfully!
Rows and columns: (10841, 13)
['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type', 'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver', 'Android Ver']

In [19]:

# Convert required columns to numeric values
df4["Rating"] = pd.to_numeric(df4["Rating"], errors="coerce")
df4["Reviews"] = pd.to_numeric(df4["Reviews"], errors="coerce")

# Clean and convert Installs
df4["Installs"] = (
    df4["Installs"].astype(str)
    .str.replace(",", "", regex=False)
    .str.replace("+", "", regex=False)
)
df4["Installs"] = pd.to_numeric(df4["Installs"], errors="coerce")

# Convert app size to MB
def convert_size_to_mb(value):
    value = str(value).strip().upper()

    if value.endswith("M"):
        return pd.to_numeric(value[:-1], errors="coerce")
    elif value.endswith("K"):
        return pd.to_numeric(value[:-1], errors="coerce") / 1024
    else:
        return np.nan

df4["Size_MB"] = df4["Size"].apply(convert_size_to_mb)

# Convert Last Updated to datetime
df4["Last Updated"] = pd.to_datetime(
    df4["Last Updated"], errors="coerce"
)

# Apply Task 4 filters
filtered4 = df4[
    (df4["Rating"] >= 4.2) &
    (~df4["App"].astype(str).str.contains(r"\d", regex=True)) &
    (df4["Category"].str.startswith(("T", "P"))) &
    (df4["Reviews"] > 1000) &
    (df4["Size_MB"].between(20, 80))
].copy()

# Remove rows missing required values
filtered4 = filtered4.dropna(
    subset=["Installs", "Last Updated", "Category"]
)

print("Rows after filtering:", len(filtered4))
print("\nCategories included:")
print(sorted(filtered4["Category"].unique()))
print("\nSize range in MB:")
print(filtered4["Size_MB"].min(), "to", filtered4["Size_MB"].max())

Rows after filtering: 139

Categories included:
['PARENTING', 'PERSONALIZATION', 'PHOTOGRAPHY', 'PRODUCTIVITY', 'TOOLS', 'TRAVEL_AND_LOCAL']

Size range in MB:
20.0 to 62.0

In [20]:

# Translate category names for the chart legend
category_translation4 = {
    "TRAVEL_AND_LOCAL": "Voyage et local",
    "PRODUCTIVITY": "Productividad",
    "PHOTOGRAPHY": "写真"
}

filtered4["Category_Display"] = (
    filtered4["Category"]
    .map(category_translation4)
    .fillna(filtered4["Category"])
)

# Create month from Last Updated
filtered4["Month"] = (
    filtered4["Last Updated"]
    .dt.to_period("M")
    .dt.to_timestamp()
)

# Aggregate installs by month and category
monthly4 = (
    filtered4.groupby(
        ["Month", "Category_Display"],
        as_index=False
    )["Installs"]
    .sum()
    .sort_values("Month")
)

print("Task 4 monthly data created!")
print("Rows:", len(monthly4))
print("\nTranslated categories:")
print(sorted(monthly4["Category_Display"].unique()))
display(monthly4.head(10))

Task 4 monthly data created!
Rows: 37

Translated categories:
['PARENTING', 'PERSONALIZATION', 'Productividad', 'TOOLS', 'Voyage et local', '写真']

       Month Category_Display    Installs
0 2014-11-01               写真   1000000.0
1 2016-10-01    Productividad   1000000.0
2 2016-12-01  PERSONALIZATION   2000000.0
3 2017-03-01               写真  50000000.0
4 2017-06-01               写真  10000000.0
5 2017-07-01               写真  15000000.0
6 2017-08-01            TOOLS     50000.0
7 2017-09-01  PERSONALIZATION   1000000.0
9 2017-10-01               写真   5000000.0
8 2017-10-01  Voyage et local     50000.0

In [21]:

# Sort data by category and month
monthly4 = monthly4.sort_values(
    ["Category_Display", "Month"]
).copy()

# Previous available month's installs for each category
monthly4["Previous_Installs"] = (
    monthly4.groupby("Category_Display")["Installs"].shift(1)
)

# Calculate percentage growth
monthly4["Growth_Percent"] = (
    (monthly4["Installs"] - monthly4["Previous_Installs"])
    / monthly4["Previous_Installs"] * 100
)

# Mark growth greater than 25%
monthly4["Significant_Growth"] = (
    monthly4["Growth_Percent"] > 25
)

print("Growth calculation completed!")
display(
    monthly4[
        ["Month", "Category_Display", "Installs",
         "Previous_Installs", "Growth_Percent",
         "Significant_Growth"]
    ].head(15)
)

Growth calculation completed!

,Month,Category_Display,Installs,Previous_Installs,Growth_Percent,Significant_Growth
16,2018-03-01,PARENTING,1.000000e+05,NaN,NaN,False
19,2018-05-01,PARENTING,1.000000e+07,100000.0,9900.000000,True
26,2018-07-01,PARENTING,6.000000e+05,10000000.0,-94.000000,False
2,2016-12-01,PERSONALIZATION,2.000000e+06,NaN,NaN,False
7,2017-09-01,PERSONALIZATION,1.000000e+06,2000000.0,-50.000000,False
11,2018-01-01,PERSONALIZATION,1.000000e+07,1000000.0,900.000000,True
14,2018-02-01,PERSONALIZATION,1.000000e+07,10000000.0,0.000000,False
22,2018-06-01,PERSONALIZATION,1.000000e+07,10000000.0,0.000000,False
27,2018-07-01,PERSONALIZATION,1.150000e+07,10000000.0,15.000000,False
32,2018-08-01,PERSONALIZATION,2.000000e+07,11500000.0,73.913043,True
1,2016-10-01,Productividad,1.000000e+06,NaN,NaN,False
15,2018-02-01,Productividad,1.000000e+05,1000000.0,-90.000000,False
23,2018-06-01,Productividad,1.500000e+07,100000.0,14900.000000,True
28,2018-07-01,Productividad,2.760000e+08,15000000.0,1740.000000,True
33,2018-08-01,Productividad,1.705000e+09,276000000.0,517.753623,True

In [23]:

# Create a complete monthly timeline
all_months = pd.date_range(
    monthly4["Month"].min(),
    monthly4["Month"].max(),
    freq="MS"
)

# Pivot data for the stacked area chart
area_data = monthly4.pivot(
    index="Month",
    columns="Category_Display",
    values="Installs"
).reindex(all_months).fillna(0)

area_data.index.name = "Month"

# Identify months with >25% growth in any category
growth_months = set(
    monthly4.loc[
        monthly4["Significant_Growth"],
        "Month"
    ]
)

# Create stacked area chart
fig4 = go.Figure()

fig4_months = area_data.index

for category in area_data.columns:
    fig4.add_trace(
        go.Scatter(
            x=fig4_months,
            y=area_data[category],
            mode="lines",
            name=category,
            stackgroup="installs",
            hovertemplate=(
                "Month: %{x|%b %Y}<br>"
                + category
                + ": %{y:,.0f}<extra></extra>"
            )
        )
    )

# Highlight months with significant growth
for month in growth_months:
    if month in area_data.index:
        fig4.add_vrect(
            x0=month,
            x1=month + pd.offsets.MonthBegin(1),
            fillcolor="red",
            opacity=0.16,
            line_width=0,
            layer="above"
        )

fig4.update_layout(
    title="Monthly Installs by App Category — Task 4",
    xaxis_title="Month",
    yaxis_title="Installs",
    hovermode="x unified",
    template="plotly_white",
    height=650,
    legend_title="App Category"
)


from datetime import datetime
from zoneinfo import ZoneInfo

now_ist = datetime.now(ZoneInfo("Asia/Kolkata"))
current_minutes = now_ist.hour * 60 + now_ist.minute

start_minutes = 16 * 60  # 4 PM
end_minutes = 18 * 60    # 6 PM

if start_minutes <= current_minutes < end_minutes:
    print("Task 4 chart is available now (4 PM - 6 PM IST).")
    fig4.show()
else:
    print("Task 4 chart is hidden. Available daily from 4 PM to 6 PM IST.")

Task 4 chart is available now (4 PM - 6 PM IST).

In [24]:

import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from datetime import datetime
from zoneinfo import ZoneInfo

url = "https://raw.githubusercontent.com/vaish-vkb/Google-Play-Store-Analytics/main/Play%20Store%20Data.csv"

df5 = pd.read_csv(url)

print("Task 5 dataset loaded successfully!")
print("Rows and columns:", df5.shape)
print(df5.columns.tolist())

Task 5 dataset loaded successfully!
Rows and columns: (10841, 13)
['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type', 'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver', 'Android Ver']

In [25]:

# Convert rating and reviews to numeric
df5["Rating"] = pd.to_numeric(df5["Rating"], errors="coerce")
df5["Reviews"] = pd.to_numeric(df5["Reviews"], errors="coerce")

# Clean and convert installs to numeric
df5["Installs"] = (
    df5["Installs"].astype(str)
    .str.replace(",", "", regex=False)
    .str.replace("+", "", regex=False)
)
df5["Installs"] = pd.to_numeric(df5["Installs"], errors="coerce")

# Convert app size to MB
def size_to_mb(value):
    value = str(value).strip().upper()

    if value.endswith("M"):
        return pd.to_numeric(value[:-1], errors="coerce")
    elif value.endswith("K"):
        return pd.to_numeric(value[:-1], errors="coerce") / 1024
    return np.nan

df5["Size_MB"] = df5["Size"].apply(size_to_mb)

# Convert Last Updated to datetime
df5["Last Updated"] = pd.to_datetime(
    df5["Last Updated"], errors="coerce"
)

# Apply rating, size, and January filters
filtered5 = df5[
    (df5["Rating"] >= 4.0) &
    (df5["Size_MB"] >= 10) &
    (df5["Last Updated"].dt.month == 1)
].copy()

filtered5 = filtered5.dropna(
    subset=["Category", "Installs", "Reviews", "Rating"]
)

print("Rows after filtering:", len(filtered5))
print("\nDate range:")
print(filtered5["Last Updated"].min(), "to",
      filtered5["Last Updated"].max())
print("\nCategories remaining:", filtered5["Category"].nunique())

Rows after filtering: 131

Date range:
2014-01-13 00:00:00 to 2018-01-31 00:00:00

Categories remaining: 22

In [26]:

# Group apps by category
category_summary5 = (
    filtered5.groupby("Category", as_index=False)
    .agg(
        Average_Rating=("Rating", "mean"),
        Total_Reviews=("Reviews", "sum"),
        Total_Installs=("Installs", "sum")
    )
)

# Sort by total installs and select top 10 categories
top10_categories5 = (
    category_summary5
    .sort_values("Total_Installs", ascending=False)
    .head(10)
    .copy()
)

print("Top 10 categories by total installs:")
display(top10_categories5)

Top 10 categories by total installs:

           Category  Average_Rating  Total_Reviews  Total_Installs
7            FAMILY        4.395455      4544623.0     182494820.0
19           SPORTS        4.342857      1982017.0     120511000.0
10             GAME        4.313333      2397589.0     115691000.0
5     ENTERTAINMENT        4.250000      1238948.0      51000000.0
14  PERSONALIZATION        4.475000       155996.0      15060000.0
15      PHOTOGRAPHY        4.150000       563720.0      10500000.0
11        LIFESTYLE        4.380000        42809.0       5071000.0
4         EDUCATION        4.400000        57645.0       2000000.0
17         SHOPPING        4.200000        19950.0       2000000.0
20            TOOLS        4.200000         8010.0       1010000.0

In [27]:

# Prepare data for grouped bar chart
chart_data5 = top10_categories5.melt(
    id_vars="Category",
    value_vars=["Average_Rating", "Total_Reviews"],
    var_name="Metric",
    value_name="Value"
)

# Create grouped bar chart
fig5 = px.bar(
    chart_data5,
    x="Category",
    y="Value",
    color="Metric",
    barmode="group",
    title="Task 5: Average Rating vs Total Reviews — Top 10 Categories",
    labels={
        "Category": "App Category",
        "Value": "Value",
        "Metric": "Metric"
    },
    hover_data=["Value"]
)

fig5.update_layout(
    xaxis_tickangle=-45,
    height=650,
    legend_title="Comparison",
    template="plotly_white"
)

# Display chart only from 3 PM to 5 PM IST
from datetime import datetime
from zoneinfo import ZoneInfo

now_ist = datetime.now(ZoneInfo("Asia/Kolkata"))
current_minutes = now_ist.hour * 60 + now_ist.minute

if 15 * 60 <= current_minutes < 17 * 60:
    print("Task 5 chart is available now (3 PM - 5 PM IST).")
    fig5.show()
else:
    print("Task 5 chart is hidden. Available daily from 3 PM to 5 PM IST.")

Task 5 chart is hidden. Available daily from 3 PM to 5 PM IST.

In [28]:
fig5.show()